// NOTIFICATION actions
export const SET_NOTIFICATION_ACTION = 'SET_NOTIFICATION_ACTION';
export const REMOVE_NOTIFICATION_ACTION = 'REMOVE_NOTIFICATION_ACTION';
export const CLEAR_NOTIFICATIONS_ACTION = 'CLEAR_NOTIFICATION_ACTION';

// USER actions
export const SET_USER_ACTION = 'SET_USER_ACTION';
